import FromTourGuides from "@/components/hleper/FromTourGuides";
import MainHeaderList from "@/components/list/MainHeaderList";
import Footer from "@/components/mainSections/Footer";
import Subscribe from "@/components/mainSections/Subscribe";
import WhyChooseUs from "@/components/mainSections/WhyChooseUs";
import HeaderSections from "@/components/parts/HeaderSections";
import FromPassportApp from "@/components/passportApplication/FromPassportApp";
import { baseUrl, fetchApi } from "@/utils/ferchApi";
import Head from "next/head";
import React from "react";

function Passport_application() {
  return (
    <>
      <Head>
        <title>Passport application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainHeaderList title={"Passport application"} />
      <HeaderSections
        titel={"Passport application"}
        desc="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
      />

      <FromPassportApp />
      <WhyChooseUs />
      <Subscribe />
      <Footer />
    </>
  );
}

export default Passport_application;
